VERBOSE = False
QUIET = True

GENERATION = 10

POP_PER_GEN = 20
KEEP_CLEAN_RATIO = 0.2
KEEP_MUT_RATIO = 0.5
BREED_FROM_RATIO = 0.5

CASE_PER_SUITE = 10

#########################################################
KEEP_CLEAN = round(POP_PER_GEN * KEEP_CLEAN_RATIO)
KEEP_MUT = round(POP_PER_GEN * KEEP_MUT_RATIO)
BREED_FROM = round(POP_PER_GEN * BREED_FROM_RATIO)

VERBOSE &= not QUIET

def print_settings () :
    print("GENERATION", GENERATION)
    print("POPULATION SIZE PER GENERATION", POP_PER_GEN)
    print("KEEP CLEAN RATIO", KEEP_CLEAN_RATIO)
    print("KEEP WITH MUTATION RATIO", KEEP_MUT_RATIO)
    print("BREED FROM RATIO", BREED_FROM_RATIO)
    print("CASE PER SUITE", CASE_PER_SUITE)
